spring:
  application:
    name: kitchensink
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/kitchensink}
      auto-index-creation: false

mongock:
  migration-scan-package:
    - com.example.kitchensink.migrations

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
